"""init database

Revision ID: 0b9b86c3f000
Revises: None
Create Date: 2016-02-29 19:16:34.400000

"""

# revision identifiers, used by Alembic.
revision = '0b9b86c3f000'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ECG',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('file_name', sa.String(length=100), nullable=True),
                    sa.Column('date', sa.String(length=20), nullable=True),
                    sa.Column('time', sa.String(length=30), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_ECG_file_name'), 'ECG', ['file_name'], unique=False)
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('nickname', sa.String(length=64), nullable=True),
                    sa.Column('sex', sa.String(length=5), nullable=True),
                    sa.Column('age', sa.String(length=5), nullable=True),
                    sa.Column('height', sa.String(length=8), nullable=True),
                    sa.Column('weight', sa.String(length=8), nullable=True),
                    sa.Column('email', sa.String(length=120), nullable=True),
                    sa.Column('password', sa.String(length=20), nullable=True),
                    sa.Column('about_me', sa.String(length=140), nullable=True),
                    sa.Column('member_since', sa.DateTime(), nullable=True),
                    sa.Column('last_seen', sa.DateTime(), nullable=True),
                    sa.Column('avatar', sa.String(length=40), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_nickname'), 'user', ['nickname'], unique=False)
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=False)
    op.create_index(op.f('ix_user_sex'), 'user', ['sex'], unique=False)
    op.create_table('post',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('body', sa.String(length=140), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_index(op.f('ix_user_sex'), table_name='user')
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.drop_index(op.f('ix_user_nickname'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_ECG_file_name'), table_name='ECG')
    op.drop_table('ECG')
    ### end Alembic commands ###
