"""modify column

Revision ID: 280fddb26a57
Revises: None
Create Date: 2016-02-29 15:13:08.460000

"""

# revision identifiers, used by Alembic.
revision = '280fddb26a57'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migrate_version')
    op.create_index(op.f('ix_ECG_file_name'), 'ECG', ['file_name'], unique=False)
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_sex'), 'user', ['sex'], unique=False)
    op.drop_index('ix_user_nickname', table_name='user')
    op.create_index(op.f('ix_user_nickname'), 'user', ['nickname'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_nickname'), table_name='user')
    op.create_index('ix_user_nickname', 'user', ['nickname'], unique=1)
    op.drop_index(op.f('ix_user_sex'), table_name='user')
    op.drop_column('user', 'member_since')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_index(op.f('ix_ECG_file_name'), table_name='ECG')
    op.create_table('migrate_version',
                    sa.Column('repository_id', sa.VARCHAR(length=250), nullable=False),
                    sa.Column('repository_path', sa.TEXT(), nullable=True),
                    sa.Column('version', sa.INTEGER(), nullable=True),
                    sa.PrimaryKeyConstraint('repository_id')
                    )
    ### end Alembic commands ###
